name: Next.js UI CI/CD
on:
  push:
    branches: [main]
    paths:
      - "recipe-nextjs-ui/**"
  pull_request:
    branches: [main]
    paths:
      - "recipe-nextjs-ui/**"
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # First handle root level dependencies (including Husky)
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
      - name: Install root dependencies
        run: npm install

      # Then handle UI project
      - name: Install UI dependencies
        working-directory: ./recipe-nextjs-ui
        run: npm install
      - name: Run lint
        working-directory: ./recipe-nextjs-ui
        run: npm run lint
      - name: Build
        working-directory: ./recipe-nextjs-ui
        run: npm run build
      - name: Deploy to Vercel
        if: github.ref == 'refs/heads/main'
        working-directory: ./recipe-nextjs-ui
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: npx vercel --token ${VERCEL_TOKEN} --prod
